import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Poppins } from 'next/font/google';
import {Space_Grotesk} from 'next/font/google';


const poppins = Poppins({
  weight: ['400', '700'],
  subsets: ['latin'],
});

const spaceGrotesk = Space_Grotesk({
  weight: ['400', '700'],
  subsets: ['latin'],
});


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className}  ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="overflow-x-hidden h-screen w-screen bg-gradient-to-r from-white via-gray-100 to-gray-300">
          <div className={`h-[60px] ${spaceGrotesk.className}`}>
            <Navbar />
          </div>
          <div className="h-[calc(100vh-50px)] ">{children}</div>
        </div>
      </body>
    </html>
  );
}
